### ISSUE TITLE
Undefined _uvs in AnimatedSprite

### ISSUE THREAD

**Issue by NordMagnus** [mattjennings/svelte-pixi#28]
When creating an AnimatedSprite using a sprite sheet, I get the error message below:

```lang.console
    Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_uvs')
    at AnimatedSprite2.updateTexture (AnimatedSprite.ts:304:34)
    at AnimatedSprite2.set (AnimatedSprite.ts:407:14)
    at new AnimatedSprite2 (AnimatedSprite.ts:138:14)
    at instance_1 (AnimatedSprite.svelte:63:20)
    at init (index.mjs:1886:11)
    at new AnimatedSprite (AnimatedSprite.svelte:95:65)
```

from line 304 in `AnimatedSprite.ts`

```js
    this.uvs = this._texture._uvs.uvsFloat32;
```

My `AnimatedSprite` declaration looks like this:

```svelte
<Application {width} {height}>
  <Loader resources={['/assets/coin-spritesheet.json']}>
    <Text text="Hello World" anchor={0.5} x={width/2} y={height/2} style={{ fill: 'white' }} />
    <AnimatedSprite
      textures={getResource('/assets/coin-spritesheet.json').animations['flip-a-coin']}
      playing
      animationSpeed={0.1}
      x={0}
      y={0}
      anchor={0.5}
      scale={1}
    />
  </Loader>
</Application>
```

**Comment by NordMagnus** [comment]
I realized my problem: forgot to put `spritesheet` before animations in the line where I get the resource. Should be:

```js
textures={getResource('/assets/coin-spritesheet.json').spritesheet.animations['flip-a-coin']}
```
